// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SSPlayerForRPGMV","status":true,"description":"SpriteStudioで作成されたアニメーションを再生できるようにするプラグインです。","parameters":{"Animation File Path":"img/animations/ssas"}},
{"name":"ChangeActorBattleAnimationToSsPlayer","status":true,"description":"サイドビュー戦闘時のアクター側アニメーションをSpriteStudioアニメーションに差し替えるプラグインです。","parameters":{"Suffix(walk)":"walk","Suffix(wait)":"wait","Suffix(chant)":"chant","Suffix(guard)":"guard","Suffix(damage)":"damage","Suffix(evade)":"evade","Suffix(thrust)":"thrust","Suffix(swing)":"swing","Suffix(missile)":"missile","Suffix(skill)":"skill","Suffix(spell)":"spell","Suffix(item)":"item","Suffix(escape)":"escape","Suffix(victory)":"victory","Suffix(dying)":"dying","Suffix(abnormal)":"abnormal","Suffix(sleep)":"sleep","Suffix(dead)":"dead","HideWeaponGraphics":"ON","Loop(dead)":"OFF","Loop(victory)":"ON"}}
];
